# Generated by Django 4.2.3 on 2023-07-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=64)),
                ('event_id', models.CharField(max_length=64)),
                ('event_date', models.CharField(max_length=64)),
                ('event_country', models.CharField(default='peaky', max_length=64)),
                ('event_lat', models.FloatField()),
                ('event_lon', models.FloatField()),
                ('desc', models.TextField()),
                ('created_at', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlightList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=64)),
                ('flights_going', models.JSONField()),
                ('flights_backhome', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='WeatherEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=64)),
                ('event_id', models.CharField(max_length=64)),
                ('event_Temperature', models.FloatField()),
                ('event_Humidity', models.FloatField()),
            ],
        ),
    ]
